language: python
sudo: false
dist: trusty
python:
    - "2.7"
install:
    - pip install zc.buildout
    - buildout bootstrap
    - buildout
script:
    - bin/test -v
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
