language: python
sudo: false
dist: xenial
python:
    - "2.7"
    - "3.6"
    - "3.7"
install:
    - pip install zc.buildout coverage coveralls
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v
after_success:
  - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
