language: python
sudo: false
dist: trusty
python:
    - "2.7"
install:
    - pip install zc.buildout coverage coveralls
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v
after_success:
  - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
